name: code-containers

services:
  server:
    build: .
    ports:
      - 3000:3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
  proxy:
    image: openresty/openresty:alpine-fat
    env_file: .env
    ports:
      - 80:80
    volumes:
      - ./proxy.conf:/etc/nginx/conf.d/proxy.conf
    network_mode: host
