name: code-containers

services:
  server:
    build: ../server
    env_file: ../.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
  proxy:
    build: ../proxy
    env_file: ../.env
    ports:
      - 80:80
  frontend:
    build: ../frontend
