name: code-containers

services:
  server:
    build: ../server
    env_file: ../.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
  proxy:
    image: nginx:alpine
    env_file: ../.env
    ports:
      - 80:80
    volumes:
      - ../proxy/proxy.conf:/etc/nginx/templates/proxy.conf
    entrypoint: /bin/sh -c 'sed "s/{PROXY_DOMAIN}/$$PROXY_DOMAIN/" etc/nginx/templates/proxy.conf > etc/nginx/conf.d/default.conf && nginx -g "daemon off;"'
  frontend:
    build: ../frontend
