name: code-containers

services:
  server:
    build: ..
    env_file: ../.env
    ports:
      - 3000:3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
  proxy:
    build: ../proxy
    env_file: ../.env
    ports:
      - 80:80
    network_mode: host
